spring:
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
server:
  port: 8080

##超级管理员账号密码
admin:
  account: Lain
  password: LainAdmin